# Generated by Django 3.1 on 2020-08-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
